In [7]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [11]:
data=np.random.randint(0,100,(10,2))
data

array([[69, 19],
       [ 2, 10],
       [83, 24],
       [35, 39],
       [29, 80],
       [ 3, 33],
       [29, 91],
       [83, 94],
       [74, 70],
       [62, 46]])

In [12]:
scaler_model=MinMaxScaler()

In [14]:
scaler_model.fit(data)

C:\Users\DELL\Anaconda2\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


MinMaxScaler(copy=True, feature_range=(0, 1))

In [15]:
scaler_model.transform(data)

array([[0.82716049, 0.10714286],
       [0.        , 0.        ],
       [1.        , 0.16666667],
       [0.40740741, 0.3452381 ],
       [0.33333333, 0.83333333],
       [0.01234568, 0.27380952],
       [0.33333333, 0.96428571],
       [1.        , 1.        ],
       [0.88888889, 0.71428571],
       [0.74074074, 0.42857143]])

In [16]:
scaler_model.fit_transform(data)

array([[0.82716049, 0.10714286],
       [0.        , 0.        ],
       [1.        , 0.16666667],
       [0.40740741, 0.3452381 ],
       [0.33333333, 0.83333333],
       [0.01234568, 0.27380952],
       [0.33333333, 0.96428571],
       [1.        , 1.        ],
       [0.88888889, 0.71428571],
       [0.74074074, 0.42857143]])

In [17]:
import pandas as pd

In [20]:
data=pd.DataFrame(data=np.random.randint(0,101,(50,4)),columns=['f1','f2','f3','label'])

In [23]:
data.head()

f1  f2  f3  label
0  58  81  87     12
1  11   3  15     85
2  82  78  88     31
3  55  99  27     49
4   1  29  90      3

In [28]:
x=data[['f1','f2','f3']]
y=data['label']

In [29]:
from sklearn.model_selection import train_test_split

In [30]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [32]:
x_train.shape

(40, 3)